version: '3.8'

services:
  laravel-app:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-backend:/var/www/html
    depends_on:
      - mysql
      - redis

  django-app:
    build:
      context: ./django-backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./django-backend:/app
    depends_on:
      - postgres
      - redis

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: chat_matching
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: matching_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql-data:
  postgres-data: