name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Install Composer dependencies
      run: |
        cd laravel-backend
        composer install --prefer-dist --no-progress --no-suggest
    
    - name: Copy .env
      run: |
        cd laravel-backend
        cp .env.example .env
        php artisan key:generate
    
    - name: Run Laravel tests
      run: |
        cd laravel-backend
        php artisan test
  
  django-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd django-backend
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Django tests
      run: |
        cd django-backend
        python manage.py test